
<link href="/css/swagger.css" media="screen" rel="stylesheet" type="text/css" />
<script src='js/jquery/jquery.js' type='text/javascript'></script>
<script src='js/jquery/jquery-ui-1.8.20.custom.min.js' type='text/javascript'></script>
  <script type="text/javascript">
      $(function () {
          if (this.host == "localhost" || this.host == "" || typeof this.host == 'undefined') {
              this.host = window.location.host;
          }
          var url = window.location.origin + "/js/swagger/booking.json";
          // Pre load translate...
          if(window.SwaggerTranslator) {
            window.SwaggerTranslator.translate();
          }
          window.swaggerUi = new SwaggerUi({
            url: url,
            dom_id: "swagger-ui-container",
            supportedSubmitMethods: ['get', 'post', 'put', 'delete', 'patch'],
            onComplete: function(swaggerApi, swaggerUi){

              if(window.SwaggerTranslator) {
                window.SwaggerTranslator.translate();
              }

              $('pre code').each(function(i, e) {
                hljs.highlightBlock(e)
              });

            },
            onFailure: function(data) {
              log("Unable to Load SwaggerUI");
            },
            docExpansion: "none",
            apisSorter: "alpha",
            showRequestHeaders: false
          });
          window.swaggerUi.load();
          setTimeout(beautify, 3000);
          function beautify () {
              $('.heading').each(function () {
                  var path = $('.path', $(this)),
                      pathParts = path.text().split('/');
                  if (pathParts[1] == 'triggerEventForItem') {
                      if (pathParts[5] != '{event}') {
                          $('a', path).text(pathParts[5]);
                      } else {
                          $('a', path).text("UNIVERSAL");
                      }
                      var desc = $('p', ($(('.markdown'), $(this).parent())[0])).text();
                      path.html(path.html() +":" + desc);
                  }
              });
          }
          function log() {
            if ('console' in window) {
              console.log.apply(console, arguments);
            }
          }
      });
  </script>

<div class="swagger-section">
<div id='header'>
  <div class="swagger-ui-wrap">
    <form id='api_selector'>
      <div class='input'><input placeholder="http://example.com/api" id="input_baseUrl" name="baseUrl" type="text"/></div>
      <div class='input'><a id="explore" href="#" data-sw-translate>Explore</a></div>
    </form>
  </div>
</div>

<div id="message-bar" class="swagger-ui-wrap" data-sw-translate>&nbsp;</div>
<div id="swagger-ui-container" class="swagger-ui-wrap"></div>
</div>
<script src='/js/swagger/lib/jquery-1.8.0.min.js' type='text/javascript'></script>
<script src='/js/swagger/lib/jquery.slideto.min.js' type='text/javascript'></script>
<script src='/js/swagger/lib/jquery.wiggle.min.js' type='text/javascript'></script>
<script src='/js/swagger/lib/jquery.ba-bbq.min.js' type='text/javascript'></script>
<script src='/js/swagger/lib/handlebars-2.0.0.js' type='text/javascript'></script>
<script src='/js/swagger/lib/underscore-min.js' type='text/javascript'></script>
<script src='/js/swagger/lib/backbone-min.js' type='text/javascript'></script>
<script src='/js/swagger/swagger-ui.min.js' type='text/javascript'></script>
<script src='/js/swagger/lib/highlight.7.3.pack.js' type='text/javascript'></script>
<script src='/js/swagger/lib/marked.js' type='text/javascript'></script>
